export const mockData = {
  items: [
    {
      categoryid: 1,
      categoryname: 'Frontend Development',
      categorylevel: 1,
      categoryparentid: 0,
      remark: 'This is a sub-category of Web Development.',
    },
    {
      categoryid: 2,
      categoryname: 'Backend Development',
      categorylevel: 1,
      categoryparentid: 0,
      remark: 'This is a sub-category of Web Development.',
    },
    {
      categoryid: 3,
      categoryname: 'HTML & CSS',
      categorylevel: 2,
      categoryparentid: 1,
      remark: 'Basics for Frontend Development.',
    },
    {
      categoryid: 4,
      categoryname: 'JavaScript',
      categorylevel: 2,
      categoryparentid: 1,
      remark: 'Essential for Web Development.',
    },
    {
      categoryid: 5,
      categoryname: 'React',
      categorylevel: 2,
      categoryparentid: 1,
      remark: 'A popular JavaScript library for building user interfaces.',
    },
    {
      categoryid: 6,
      categoryname: 'Node.js',
      categorylevel: 2,
      categoryparentid: 2,
      remark: 'JavaScript runtime for building server-side applications.',
    },
    {
      categoryid: 7,
      categoryname: 'Express',
      categorylevel: 3,
      categoryparentid: 2,
      remark: 'Web application framework for Node.js.',
    },
    {
      categoryid: 8,
      categoryname: 'Databases',
      categorylevel: 1,
      categoryparentid: 0,
      remark: 'Storage for application data.',
    },
    {
      categoryid: 9,
      categoryname: 'MongoDB',
      categorylevel: 2,
      categoryparentid: 7,
      remark: 'NoSQL database for modern applications.',
    },
    {
      categoryid: 10,
      categoryname: 'MySQL',
      categorylevel: 2,
      categoryparentid: 7,
      remark: 'Relational database management system.',
    },
    {
      categoryid: 11,
      categoryname: 'PostgreSQL',
      categorylevel: 2,
      categoryparentid: 7,
      remark: 'Open source relational database.',
    },
    {
      categoryid: 12,
      categoryname: 'Cloud Computing',
      categorylevel: 1,
      categoryparentid: 0,
      remark: 'On-demand computing resources over the internet.',
    },
    {
      categoryid: 13,
      categoryname: 'AWS',
      categorylevel: 2,
      categoryparentid: 11,
      remark: 'Comprehensive cloud services platform.',
    },
    {
      categoryid: 14,
      categoryname: 'Azure',
      categorylevel: 2,
      categoryparentid: 11,
      remark: 'Cloud computing service created by Microsoft.',
    },
    {
      categoryid: 15,
      categoryname: 'Google Cloud',
      categorylevel: 2,
      categoryparentid: 11,
      remark: 'Suite of cloud computing services by Google.',
    },
    {
      categoryid: 16,
      categoryname: 'DevOps',
      categorylevel: 1,
      categoryparentid: 0,
      remark: 'Practices for collaboration and productivity.',
    },
    {
      categoryid: 17,
      categoryname: 'Docker',
      categorylevel: 2,
      categoryparentid: 15,
      remark: 'Platform for developing, shipping, and running applications.',
    },
    {
      categoryid: 18,
      categoryname: 'Kubernetes',
      categorylevel: 2,
      categoryparentid: 15,
      remark:
        'Automate deployment, scaling, and management of containerized applications.',
    },
    {
      categoryid: 19,
      categoryname: 'CI/CD',
      categorylevel: 2,
      categoryparentid: 15,
      remark: 'Continuous integration and continuous delivery.',
    },
    {
      categoryid: 20,
      categoryname: 'Testing',
      categorylevel: 1,
      categoryparentid: 0,
      remark: 'Ensuring software quality.',
    },
    {
      categoryid: 21,
      categoryname: 'Unit Testing',
      categorylevel: 2,
      categoryparentid: 19,
      remark: 'Testing individual units of source code.',
    },
    {
      categoryid: 22,
      categoryname: 'Integration Testing',
      categorylevel: 2,
      categoryparentid: 19,
      remark: 'Testing combined parts of an application.',
    },
    {
      categoryid: 23,
      categoryname: 'E2E Testing',
      categorylevel: 2,
      categoryparentid: 19,
      remark: 'Testing the entire application from start to finish.',
    },
    {
      categoryid: 24,
      categoryname: 'UI/UX Design',
      categorylevel: 1,
      categoryparentid: 0,
      remark: 'Designing user interfaces and experiences.',
    },
    {
      categoryid: 25,
      categoryname: 'Figma',
      categorylevel: 2,
      categoryparentid: 23,
      remark: 'Interface design tool.',
    },
    {
      categoryid: 26,
      categoryname: 'Sketch',
      categorylevel: 2,
      categoryparentid: 23,
      remark: 'Digital design toolkit.',
    },
  ],
  total: 0,
}
